# Generated by Django 5.1.4 on 2025-09-14 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64, unique=True)),
                ('type', models.CharField(choices=[('account_activation', 'Account Activation'), ('account_deletion', 'Account Deletion'), ('authentication', 'Authentication'), ('password_reset', 'Password Reset')], max_length=32)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['type', 'user', 'used', 'expired_at'], name='token_app_t_type_5cdbeb_idx')],
            },
        ),
    ]
