# Generated by Django 5.1.4 on 2025-09-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
