# Generated by Django 5.1.4 on 2025-07-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_offer_app', '0002_video_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hls_playlist',
            field=models.FileField(blank=True, null=True, upload_to='videos/hls/'),
        ),
        migrations.AddField(
            model_name='video',
            name='preview_clip',
            field=models.FileField(blank=True, null=True, upload_to='videos/preview/'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='videos/thumbs/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/original/'),
        ),
    ]
