# Generated by Django 5.1.4 on 2025-07-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_offer_app', '0003_video_hls_playlist_video_preview_clip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
    ]
