# Generated by Django 5.1.4 on 2025-07-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_offer_app', '0004_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='sprite_sheet',
            field=models.FileField(blank=True, help_text='Contact sheet image generated automatically', null=True, upload_to='videos/sprites/'),
        ),
    ]
