# Generated by Django 5.1.4 on 2025-07-01 21:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_offer_app', '0005_video_sprite_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='available_resolutions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, help_text="List of HLS resolutions generated, e.g. ['1080p','720p']", size=None),
        ),
    ]
