# Generated by Django 5.1.4 on 2025-07-02 09:12

import video_offer_app.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_offer_app', '0006_video_available_resolutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='hls_playlist',
            field=models.FileField(blank=True, null=True, storage=video_offer_app.storage_backends.OverwriteStorage(), upload_to='videos/hls/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='preview_clip',
            field=models.FileField(blank=True, null=True, storage=video_offer_app.storage_backends.OverwriteStorage(), upload_to='videos/preview/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, storage=video_offer_app.storage_backends.OverwriteStorage(), upload_to='videos/thumbs/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=video_offer_app.storage_backends.OverwriteStorage(), upload_to='videos/original/'),
        ),
    ]
