# Generated by Django 5.1.4 on 2025-07-02 09:31

import video_offer_app.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_offer_app', '0007_alter_video_hls_playlist_alter_video_preview_clip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='sprite_sheet',
            field=models.FileField(blank=True, help_text='Contact sheet image generated automatically', null=True, storage=video_offer_app.storage_backends.OverwriteStorage(), upload_to='videos/sprites/'),
        ),
    ]
