# Generated by Django 5.1.4 on 2025-09-13 10:35

import video_app.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('genre', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('duration', models.FloatField(default=0.0)),
                ('video_file', models.FileField(blank=True, null=True, storage=video_app.storage_backends.OverrideStorage(), upload_to='videos/originals/')),
                ('hls_playlist', models.FileField(blank=True, null=True, storage=video_app.storage_backends.OverrideStorage(), upload_to='videos/hls/')),
                ('quality_levels', models.JSONField(blank=True, default=list)),
                ('preview', models.FileField(blank=True, storage=video_app.storage_backends.OverrideStorage(), upload_to='videos/previews/')),
                ('thumbnail', models.ImageField(blank=True, storage=video_app.storage_backends.OverrideStorage(), upload_to='videos/thumbs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
