# Generated by Django 5.1.4 on 2025-07-02 21:38

import datetime
import django.contrib.postgres.fields
import django.db.models.deletion
import video_app.storage_backends
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('genre', models.CharField(default='', max_length=80)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500)),
                ('video_file', models.FileField(blank=True, null=True, storage=video_app.storage_backends.OverwriteStorage(), upload_to='videos/original/')),
                ('hls_playlist', models.FileField(blank=True, null=True, storage=video_app.storage_backends.OverwriteStorage(), upload_to='videos/hls/')),
                ('preview_clip', models.FileField(blank=True, null=True, storage=video_app.storage_backends.OverwriteStorage(), upload_to='videos/preview/')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, storage=video_app.storage_backends.OverwriteStorage(), upload_to='videos/thumbs/')),
                ('sprite_sheet', models.FileField(blank=True, help_text='Contact sheet image generated automatically', null=True, storage=video_app.storage_backends.OverwriteStorage(), upload_to='videos/sprites/')),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('available_resolutions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, help_text="List of HLS resolutions generated, e.g. ['1080p','720p']", size=None)),
            ],
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_position', models.IntegerField(default=0, help_text='Last playback time in seconds')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this position was last updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='video_app.video')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'video')},
            },
        ),
    ]
