# Generated by Django 5.1.4 on 2025-07-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoProgress',
        ),
    ]
