# Generated by Django 5.1.4 on 2025-07-04 07:46

import django.contrib.postgres.fields
import video_app.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0004_alter_video_available_resolutions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='available_resolutions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='hls_playlist',
            field=models.FileField(blank=True, null=True, storage=video_app.storage_backends.OverwriteStorage(), upload_to='videos/hls/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='preview_clip',
            field=models.FileField(blank=True, null=True, storage=video_app.storage_backends.OverwriteStorage(), upload_to='videos/preview/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='sprite_sheet',
            field=models.FileField(blank=True, null=True, storage=video_app.storage_backends.OverwriteStorage(), upload_to='videos/sprites/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, storage=video_app.storage_backends.OverwriteStorage(), upload_to='videos/thumbs/'),
        ),
    ]
