# Generated by Django 5.1.4 on 2025-07-04 07:58

import video_app.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0005_alter_video_available_resolutions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=video_app.storage_backends.OverwriteStorage(), upload_to='videos/original/'),
        ),
    ]
