# Generated by Django 5.1.4 on 2025-07-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0006_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
    ]
