# Generated by Django 5.1.4 on 2025-09-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0008_alter_video_description_alter_video_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='video',
            name='available_resolutions',
        ),
        migrations.RemoveField(
            model_name='video',
            name='preview_clip',
        ),
        migrations.RemoveField(
            model_name='video',
            name='sprite_sheet',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail_image',
        ),
        migrations.AddField(
            model_name='video',
            name='preview',
            field=models.FileField(blank=True, upload_to='videos/previews/'),
        ),
        migrations.AddField(
            model_name='video',
            name='quality_levels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='videos/thumbs/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='video',
            name='genre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='hls_playlist',
            field=models.FileField(blank=True, null=True, upload_to='videos/hls/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/originals/'),
        ),
    ]
