# Generated by Django 5.1.4 on 2025-07-03 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video_app', '0002_delete_videoprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_position', models.IntegerField(default=0, help_text='Last playback time in seconds')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this position was last updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='video_app.video')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'video')},
            },
        ),
    ]
