# Generated by Django 5.1.4 on 2025-09-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_progress_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprogress',
            name='relative_position',
            field=models.FloatField(default=0.0),
        ),
    ]
