# Generated by Django 5.1.4 on 2025-07-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_progress_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
